# Generated by Django 5.1.1 on 2024-10-04 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('superheroes', '0002_authuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='authuser_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='authuser_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
