# Generated by Django 5.1.1 on 2024-10-07 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_alter_authuser_groups_alter_authuser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
