# Generated by Django 5.1.1 on 2024-10-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0004_alter_authuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='user',
        ),
    ]
