# Generated by Django 5.1.1 on 2024-10-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0005_remove_authuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='role',
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
